### PR TITLE
fix: workspace hard delete nits

### LINKED ISSUE #192: nits with workspace hard delete
from @danbarr 
- Nice. One suggestion on the confirmation text, maybe instead of "You will lose any custom instructions, or other configuration.", say "You will lose any custom instructions and prompt history."  ? "or other configuration" is a little vague
- Oh minor thing too, I noticed the Archive button is active on the default workspace but if you click it you get an error "Cannot delete default workspace", think that should be "Cannot archive the default workspace"?
- One more nit: the subtext under custom instructions, "augment it's behavior" -> "augment its behavior"

### PR DESCRIPTION
**Pull request by alex-mcgovern**
closes #192

### CODE REVIEW

File: src/features/workspace/components/archive-workspace.tsx [hunk 1]
```diff
@@ -1,15 +1,62 @@
...
+  workspaceName,
+}: {
+  workspaceName: string;
+  activeWorkspaceName: string;
+}) {
+  if (workspaceName === activeWorkspaceName) {
+    return "Cannot archive the active workspace";
+  }
+  if (workspaceName === "default") {
+    return "Cannot archive the default workspace";
```
Comment (peppescg) [inline src/features/workspace/components/archive-workspace.tsx:29]: I guess we can use the BE error message here, cause it is semantically correct

Comment (alex-mcgovern) [reply src/features/workspace/components/archive-workspace.tsx:29]: The BE error is `Cannot delete default workspace` which is actually a remnant, and I was about to open a PR to fix separate to this.

Comment (peppescg) [reply src/features/workspace/components/archive-workspace.tsx:29]: Right 🤔 I don't know why I remember that it was correct

**Review by peppescg — APPROVED** [review]

File: src/features/workspace/components/archive-workspace.tsx (hunk 1 above)
Comment (peppescg) [reply src/features/workspace/components/archive-workspace.tsx:29]: Anyways we can update the BE message too, but I agree on this change for now

Comment (alex-mcgovern) [reply src/features/workspace/components/archive-workspace.tsx:29]: https://github.com/stacklok/codegate/pull/764
