### PR TITLE
fix: show banner in archived workspace

### LINKED ISSUE #164: bug: you can navigate to an archived workspace, but there is no visual feedback that it is archived

### PR DESCRIPTION
**Pull request by alex-mcgovern**
Closes #164 

https://github.com/user-attachments/assets/fcf25473-3ff9-4137-9422-92c58dc7e8ed

### CODE REVIEW

File: src/features/workspace/hooks/use-archived-workspaces.ts [hunk 1]
```diff
@@ -1,14 +1,20 @@
...
 
-export const useArchivedWorkspaces = () => {
+export function useArchivedWorkspaces<T = V1ListArchivedWorkspacesResponse>({
+  select,
+}: {
+  select?: (data: V1ListArchivedWorkspacesResponse) => T;
+} = {}) {
   return useQuery({
     ...v1ListArchivedWorkspacesOptions(),
-    refetchInterval: 5_000,
```
Comment (kantord) [inline src/features/workspace/hooks/use-archived-workspaces.ts:7]: :thinking:  why was this changed

**Review by kantord — APPROVED** [review]
looks great

File: src/features/workspace/hooks/use-archived-workspaces.ts (hunk 1 above)
Comment (alex-mcgovern) [reply src/features/workspace/hooks/use-archived-workspaces.ts:7]: not manually, might have been a formatter/linter
